version: "3"
services: 
  db:
    image: postgres:10.4-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: host.docker.internal
            database: graphql
            user: postgres
            password: postgres
            ssl: false
            rawAccess: true
            port: '5432'
            migrations: true